## Module submission header
### Submission preparation instructions 
_Completion of this header is mandatory, subject to a 2-point deduction to the assignment._ Only add plain text in the designated areas, i.e., replacing the relevant 'NA's. You must fill out all group member Names and Drexel email addresses in the below markdown list, under header __Module submission group__. It is required to fill out descriptive notes pertaining to any tutoring support received in the completion of this submission under the __Additional submission comments__ section at the bottom of the header. If no tutoring support was received, leave NA in place. You may as well list other optional comments pertaining to the submission at bottom. _Any distruption of this header's formatting will make your group liable to the 2-point deduction._

### Module submission group
- Group member 1
    - Name: Kahf Hussain
    - Email: knh66@drexel.edu
- Group member 2
    - Name: Naren Garapati
    - Email: ng658@drexel.edu
- Group member 3
    - Name: Nosherwan Babar
    - Email: nb3293@drexel.edu
- Group member 4
    - Name: Atharva Thoke
    - Email: aat323@drexel.edu

### Additional submission comments
- Tutoring support received: NA
- Other (other): NA

# Assignment group 1: Textual feature extraction and numerical comparison

## Module A _(35 points)_ Processing numeric data

In this module, you will be working with the demographics data from The Henry J. Kaiser Family Foundation (https://www.kff.org/) including the population of 52 locations (50 states, District of Columbia, and Puerto Rico) based on race, gender, age, and the number of adults with and without children. This data is obtained from the Census Bureau’s American Community Survey (ACS). The data is stored in a `csv` file format located in the attached `data` directory.

__A1.__ Write a function called `get_shape_and_column` that accepts a string representing the path to the demographics.csv data. This function should read the provided csv data file into a pandas dataframe and then return a tuple with three things: the data frame (`data`), the shape of the data frame (`shape`), and a list of the columns (`columns`). (3 points)

In [1]:
# A1:Function(3/3)
# get_shape_and_column('./data/demographics.csv'):data,shape,column

import pandas as pd

def get_shape_and_columns(csv_path):
    
    data = pd.read_csv(csv_path)
    shape = data.shape
    columns = data.columns.tolist()
    
    return data, shape, columns

__A2.__ _(2 points)_ To gain a better insight into the data, lets apply the function we just wrote to get our dataframe, inspect the shape and columns, and then look at the head and tail of this data (using the `.head()` and `.tail()` methods).

In [2]:
# A2:SanityCheck

# Load the data using our function
data, shape, columns = get_shape_and_columns('./data/demographics.csv')

# Output the shape and column names
print(shape)
print(columns)

(52, 18)
['Location', 'Male', 'Female', 'Adults_with_Children', 'Adults_with_No_Children', 'White', 'Black', 'Hispanic', 'Asian', 'American_Indian_or_Alaska_Native', 'Native_Hawaiian_or_Other_Pacific_Islander', 'Two_Or_More_Races', 'Age0_18', 'Age_19_25', 'Age_26_34', 'Age_35_54', 'Age_55_64', 'Age_65_plus']

In [3]:
# A2:SanityCheck

# Outputs the head of the data
data.head()

,Location,Male,Female,Adults_with_Children,Adults_with_No_Children,White,Black,Hispanic,Asian,American_Indian_or_Alaska_Native,Native_Hawaiian_or_Other_Pacific_Islander,Two_Or_More_Races,Age0_18,Age_19_25,Age_26_34,Age_35_54,Age_55_64,Age_65_plus
0,Alabama,2284900,2456500,878300,1941300,3119100,1259900.0,195700,63800.0,19800.0,NaN,81800.0,1138300,430500,536200.0,1207200,645600,783600
1,Alaska,364500,345600,153600,283800,433000,18000.0,47400,46600.0,95500.0,6300.0,63300.0,192300,63500,97900.0,183600,92400,80500
2,Arizona,3363200,3478100,1322700,2646700,3761600,270200.0,2143400,220300.0,261300.0,12500.0,172000.0,1686200,637200,815200.0,1677000,839900,1185700
3,Arkansas,1422700,1487200,602000,1096800,2109200,434100.0,220300,48100.0,13500.0,7300.0,77500.0,730600,265200,329800.0,726600,377100,480600
4,California,19113000,19600800,7955200,15981800,14305700,2061600.0,15194400,5598000.0,138100.0,122900.0,1293200.0,9363800,3697900,5240600.0,10277900,4720500,5413200

In [4]:
# A2:Inline(1/2)

# Which state is listed first in the head? Print the state name
# from this list of choices: (Alabama, Alaska, Arizona)

print("Alabama")

Alabama

In [5]:
# A2:SanityCheck

# Outputs the tail of the data
data.tail()

,Location,Male,Female,Adults_with_Children,Adults_with_No_Children,White,Black,Hispanic,Asian,American_Indian_or_Alaska_Native,Native_Hawaiian_or_Other_Pacific_Islander,Two_Or_More_Races,Age0_18,Age_19_25,Age_26_34,Age_35_54,Age_55_64,Age_65_plus
47,Washington,3589700,3650100,1522400,2920700,4976100,246900.0,916000,617900.0,68600.0,42200.0,372200.0,1701700,628700,965900.0,1899400,949100,1095000
48,West Virginia,863400,898700,322100,714100,1631600,64300.0,20400,14200.0,2000.0,NaN,28800.0,385000,148600,178300.0,448700,260600,340900
49,Wisconsin,2792400,2850600,1161900,2230900,4600500,328100.0,382000,166800.0,43500.0,NaN,120600.0,1319600,495600,643300.0,1441400,812500,930500
50,Wyoming,286600,276700,118200,214300,474400,5300.0,56100,4200.0,12100.0,NaN,11200.0,142400,48500,69400.0,133100,81500,88300
51,Puerto Rico,1570300,1734500,543200,1406500,23000,NaN,3274500,NaN,NaN,NaN,NaN,701800,327600,344300.0,849600,428200,653200

In [6]:
# A2:Inline(1/2)

# Which state is listed first in the tail? Print the state name
# from this list of choices: (Wyoming, Puerto Rico, Washington)
print("Washington")

Washington

__A3.__ _(5 points)_ As you can see, there is no `total` population column in this dataframe for each location. Therefore, let's write a function called `total_columns` that takes a dataframe and two column names and returns an updated dataframe. This function should create a new column in the provided dataframe called `total` that is the sum of the data in the two provided columns. It should return this updated data frame.

In [7]:
# A3:Function(3/5)
# total_columns('./data/demographics.csv', "Male", "Female")

def total_columns(data, column1, column2):
    
    data['total'] = data[column1] + data[column2]
    
    return data

To test your function, let's apply it to create totals for some of the fields and inspect at the results.

The pandas package provides a `.describe()` method which gives a descriptive summary of the desired column(s) (such as mean, standard deviation, min, and max values). The following code cells print these statistics for the newly created `total` columns.

In [8]:
# A3:SanityCheck

# Creates a total column for ages 35-64
data = total_columns(data, "Age_35_54", "Age_55_64")

# Uses the describe method to show the summary statistics for the newly created 'total' column
data[['total']].describe()

              total
count  5.200000e+01
mean   2.408640e+06
std    2.750352e+06
min    2.146000e+05
25%    6.786000e+05
50%    1.652950e+06
75%    2.727825e+06
max    1.499840e+07

In [9]:
# A3:SanityCheck

# Creates a total column for ages 19-34
data = total_columns(data, "Age_19_25", "Age_26_34")

# Uses the describe method to show the summary statistics for the newly created 'total' column
data[['total']].describe()

              total
count  5.200000e+01
mean   1.309954e+06
std    1.584595e+06
min    1.179000e+05
25%    3.369500e+05
50%    8.690500e+05
75%    1.487950e+06
max    8.938500e+06

In [10]:
# A3:Inline(2/5)

# Which mean total is greater, the sum of Age_35_54 + Age_55_64 or the sum of Age_19_25 + Age_26_34?
# Print either "Older" or "Younger"

print("Older")

Older

__A4:__ _(5 points)_ Next, write a function that takes a dataframe that has a `total` column and returns a tuple with four values: the location with the minimum total (`min_location`), the total for that min location (`min_total`), the location with the maximum total (`max_location`), and the total for the max location (`max_total`). Note that the locations returned should correspond to specific states (e.g., `"Alabama"`) and the totals should be numbers (e.g., `23000`)

In [11]:
# A4:Function(4/5)

def get_min_max_locations(data):

    # Find row (state) with minimum total value
    min_row = data.loc[data['total'].idxmin()]
    min_location = min_row['Location']
    min_total = min_row['total']

    # Find row (state) with maximum total value
    max_row = data.loc[data['total'].idxmax()]
    max_location = max_row['Location']
    max_total = max_row['total']

    return min_location, min_total, max_location, max_total

Let's apply the functions you have created to (1) total up the male and female population counts and (2) identify the states with the minimum and maximum totals and their total amounts.

In [12]:
# A4:SanityCheck

# Create a total column that contains Male + Female
data = total_columns(data, "Male", "Female")

# Get the min and max states
min_loc, min_total, max_loc, max_total = get_min_max_locations(data)

print("Minimum location: {} (total={})".format(min_loc, min_total))
print("Maximum location: {} (total={})".format(max_loc, max_total))

Minimum location: Wyoming (total=563300)
Maximum location: California (total=38713800)

In [13]:
# A4:Inline(1/5)

# Print the state with the smallest total (make sure to get capitalization right)?
print("Wyoming")

Wyoming

__A5.__ _(5 points)_ Our previous `total_columns` function has some limitations. First, it only lets us create a total column that is the sum of two columns. Additionally, it always names the resulting column `total`. Please write an updated `total_columns` function that takes three arguments: `data` (a dataframe), `list_of_columns` (a list of columns to total), and `total_name` (a name for the resulting total column). This function should total the values across all the columns in `list_of_columns` and put the result in the target `total_name` column.

In [14]:
# A5:Function(4/5)
def total_columns(data, list_of_columns, total_name="total"):

    data[total_name] = data[list_of_columns].sum(axis=1)

    return data

To test the function you've created, let's apply it to investigate our data. In particular, let's look at two columns `Adults_with_Children` and `Adults_with_No_Children`. It seems that the populations in these two columns do not include the children (aged younger than 18 years), and older adults (aged older than 64 years). To confirm this hypothesis, let's use our new `total_columns` function to create two total columns and then compare them. We will then look to see if there is a difference between these totals for three states: `Pennsylvania`, `Colorado`, and `Georgia`.

In [15]:
# A5:SanityCheck

# Create a total for all the adult age groups (excluding people youger than 18 or older than 64)
adult_age_group_columns = ['Age_19_25', 'Age_26_34', 'Age_35_54', 'Age_55_64']
data = total_columns(data, adult_age_group_columns, "total_adult_age_groups")

# Create a total column for adults with and without children.
adults_columns = ['Adults_with_Children', 'Adults_with_No_Children']
data = total_columns(data, adults_columns, "total_adults")

# Compute the difference between these values
data['diff'] = data['total_adult_age_groups'] - data['total_adults']

# Look at the differences for Pennsylvania, Colorado, and Georgia
print("Pennsylvania difference: {}".format(data[data['Location'] == "Pennsylvania"]['diff'].values))
print("Colorado difference: {}".format(data[data['Location'] == "Colorado"]['diff'].values))
print("Georgia difference: {}".format(data[data['Location'] == "Georgia"]['diff'].values))

Pennsylvania difference: [0.]
Colorado difference: [0.]
Georgia difference: [0.]

In [16]:
# A5:Inline(1/5)

# Is there a difference for these three states? Print "Yes" or "No"
print("No")

No

__A6:__ _(2 points)_ To investigate our hypothesis more generally, write a function called `are_columns_equal` that takes a dataframe and two columns names (for two columns we want to compare). The function should return a boolean value `are_equal` that is True if all the values for the two columns are the same and False if there is at least one difference.

In [17]:
# A6:Function(2/2)

def are_columns_equal(data, column1, column2):
    
    are_equal = (data[column1] == data[column2]).all()
    
    return are_equal

To test this function, let's apply it to test our hypothesis that`total_adult_age_groups` and `total_adults` are the same for all locations.

In [18]:
# A6:SanityCheck

print(are_columns_equal(data, 'total_adult_age_groups', 'total_adults'))

False

__A7:__ _(3 points)_ It seems that our hypothesis is not correct for all the locations. To investigate further, create a function called `get_location_difference_dict` that takes a dataframe and two column names and returns a dictionary (`location_diff_dict`) that has locations for keys and the difference (column1 value - column2 value) as values. Additionally, the dictionary should only include values for entries that have a non-zero difference (places where column1 value != column2 value).

For example, the resulting dictionary should look something like this:
```
{'Alabama': 300,
 'California': -210, 
 ...
}
```

In [19]:
# A7:Function(2/3)

def get_location_difference_dict(data, column1, column2):
    
    differences = data[column1] - data[column2]

    non_zero_diff = differences != 0

    location_diff_dict = dict(zip(data[non_zero_diff]['Location'], differences[non_zero_diff]))
    
    return location_diff_dict

Now let's apply the function you have created to see what the differences in `total_adult_age_groups` and `total_adults` look like across our data.

In [20]:
# A7:SanityCheck
get_location_difference_dict(data,'total_adult_age_groups', 'total_adults')

{'Alabama': -100.0,
 'Arizona': -100.0,
 'Arkansas': -100.0,
 'California': -100.0,
 'Delaware': -100.0,
 'Florida': -100.0,
 'Idaho': 100.0,
 'Illinois': 100.0,
 'Iowa': 100.0,
 'Kansas': -100.0,
 'Kentucky': -100.0,
 'Louisiana': -100.0,
 'Minnesota': -100.0,
 'Montana': 100.0,
 'Nebraska': -100.0,
 'New Mexico': 100.0,
 'North Carolina': -200.0,
 'North Dakota': -100.0,
 'Oklahoma': 100.0,
 'Oregon': 100.0,
 'South Carolina': -100.0,
 'Utah': -100.0,
 'Vermont': 100.0,
 'Virginia': -200.0}

In [21]:
# A7:Inline(1/3)

# Print the name of the state with the larger difference (greater absolute magnitude),
# "Alabama" or "North Carolina"?
print("North Carolina")

North Carolina

__A8.__ _(7 points)_ In this problem, we are going to investigate the similarity of locations using _cosine similarity_. To support these investigations, write a function called `compute_cosine_similarity` that takes a dataframe (`data`) and a list of column names (`similarity_columns`) to use when computing the cosine similarity. This function should use the provided `similarity_columns` to compute the cosine similiarity between each pair of locations. In cases where there is no population for one of the provided columns for a location in the dataframe (the corresponding value is `NaN`), replace them with `zero` using the `.fillna()` method of pandas. This function should return a list of tuples (`similarity_list`) with the following format `(<location 1>, <location 2>, <cosine similarity between them>)`.

Here is an example of what the output from this function should look like:
```
[('Alabama', 'Alaska', 0.223890893223),
 ('Alabama', 'Arizona', 0.43432273237),
 ('Alabama', 'Arkansas', 0.112312121213),
 ('Alabama', 'California', 0.45645645654623),
 ('Alabama', 'Colorado', 0.234616734),
 ('Alabama', 'Connecticut', 0.676533422),
 ('Alabama', 'Delaware', 0.1234645667),
 ...
]
```

Note that each pair of locations will appear twice in this list in different orders; e.g., `('Alabama', 'Alaska', 223890893223)` and `('Alaska', 'Alabama', 223890893223)` will both appear.

In [22]:
# A8:Function(7/7)
import numpy as np

def compute_cosine_similarity(data, similarity_columns):

    # Filling missing value with 0
    data_filled = data[similarity_columns].fillna(0)

    # Normalize rows to compute cosine similarity
    magnitudes = np.linalg.norm(data_filled.values, axis=1)
    normalized_data = data_filled.div(magnitudes, axis=0)

    similarity_list = []

    # Compute cosine similarity for all pairs of locations
    for i, loc1 in enumerate(data['Location']):
        for j, loc2 in enumerate(data['Location']):
            if i != j:
                similarity = np.dot(normalized_data.iloc[i], normalized_data.iloc[j])
                similarity_list.append((loc1, loc2, similarity))

    return similarity_list

To test our function, lets apply it to compare locations according to both race and age demographics.

In [23]:
# A8:SanityCheck

# All the race columns
race_columns = ['White', 'Black', 'Hispanic', 'Asian', 'American_Indian_or_Alaska_Native', \
                'Native_Hawaiian_or_Other_Pacific_Islander', 'Two_Or_More_Races']

race_similarity = compute_cosine_similarity(data, race_columns)
race_similarity

[('Alabama', 'Alaska', np.float64(0.9114268387800772)),
 ('Alabama', 'Arizona', np.float64(0.8532153881652852)),
 ('Alabama', 'Arkansas', np.float64(0.9827781115549581)),
 ('Alabama', 'California', np.float64(0.6910373396673632)),
 ('Alabama', 'Colorado', np.float64(0.9181663981509592)),
 ('Alabama', 'Connecticut', np.float64(0.9553103684194725)),
 ('Alabama', 'Delaware', np.float64(0.9942087439512888)),
 ('Alabama', 'District of Columbia', np.float64(0.8600337602418916)),
 ('Alabama', 'Florida', np.float64(0.9251438820043799)),
 ('Alabama', 'Georgia', np.float64(0.9837332858706161)),
 ('Alabama', 'Hawaii', np.float64(0.42667738571394787)),
 ('Alabama', 'Idaho', np.float64(0.926558166129734)),
 ('Alabama', 'Illinois', np.float64(0.9626915658026345)),
 ('Alabama', 'Indiana', np.float64(0.9634930283159449)),
 ('Alabama', 'Iowa', np.float64(0.9400898150890012)),
 ('Alabama', 'Kansas', np.float64(0.9466816358199139)),
 ('Alabama', 'Kentucky', np.float64(0.9578361229344373)),
 ('Alabama', 'Louisiana', np.float64(0.9935406238636665)),
 ('Alabama', 'Maine', np.float64(0.9309310956689741)),
 ('Alabama', 'Maryland', np.float64(0.9797117035348595)),
 ('Alabama', 'Massachusetts', np.float64(0.9518043913154131)),
 ('Alabama', 'Michigan', np.float64(0.9786086627973689)),
 ('Alabama', 'Minnesota', np.float64(0.9533492410853136)),
 ('Alabama', 'Mississippi', np.float64(0.9797211311228105)),
 ('Alabama', 'Missouri', np.float64(0.9701309473076928)),
 ('Alabama', 'Montana', np.float64(0.927279102239316)),
 ('Alabama', 'Nebraska', np.float64(0.9437434232864613)),
 ('Alabama', 'Nevada', np.float64(0.866551704056636)),
 ('Alabama', 'New Hampshire', np.float64(0.9325767465198711)),
 ('Alabama', 'New Jersey', np.float64(0.9363323061112476)),
 ('Alabama', 'New Mexico', np.float64(0.6112561934145454)),
 ('Alabama', 'New York', np.float64(0.948510378182157)),
 ('Alabama', 'North Carolina', np.float64(0.9942625373381713)),
 ('Alabama', 'North Dakota', np.float64(0.9378994924660654)),
 ('Alabama', 'Ohio', np.float64(0.972775980972594)),
 ('Alabama', 'Oklahoma', np.float64(0.9487459697176488)),
 ('Alabama', 'Oregon', np.float64(0.9294367794312076)),
 ('Alabama', 'Pennsylvania', np.float64(0.9685677854168595)),
 ('Alabama', 'Rhode Island', np.float64(0.9415911457346866)),
 ('Alabama', 'South Carolina', np.float64(0.9996860508015732)),
 ('Alabama', 'South Dakota', np.float64(0.9322526150805064)),
 ('Alabama', 'Tennessee', np.float64(0.9862861583389552)),
 ('Alabama', 'Texas', np.float64(0.7706192116570829)),
 ('Alabama', 'Utah', np.float64(0.9264901099318691)),
 ('Alabama', 'Vermont', np.float64(0.931217980975667)),
 ('Alabama', 'Virginia', np.float64(0.9884637935743699)),
 ('Alabama', 'Washington', np.float64(0.9321877685418578)),
 ('Alabama', 'West Virginia', np.float64(0.940263104059358)),
 ('Alabama', 'Wisconsin', np.float64(0.9513751984833456)),
 ('Alabama', 'Wyoming', np.float64(0.9299937398958478)),
 ('Alabama', 'Puerto Rico', np.float64(0.06454597923355135)),
 ('Alaska', 'Alabama', np.float64(0.9114268387800772)),
 ('Alaska', 'Arizona', np.float64(0.9026314648157775)),
 ('Alaska', 'Arkansas', np.float64(0.9573184971397107)),
 ('Alaska', 'California', np.float64(0.7416111800267029)),
 ('Alaska', 'Colorado', np.float64(0.9529090361921406)),
 ('Alaska', 'Connecticut', np.float64(0.9590604204992825)),
 ('Alaska', 'Delaware', np.float64(0.9324782076163212)),
 ('Alaska', 'District of Columbia', np.float64(0.6413542327967734)),
 ('Alaska', 'Florida', np.float64(0.8979329300291787)),
 ('Alaska', 'Georgia', np.float64(0.8608148284067334)),
 ('Alaska', 'Hawaii', np.float64(0.5558277164519617)),
 ('Alaska', 'Idaho', np.float64(0.9684398619035819)),
 ('Alaska', 'Illinois', np.float64(0.9445909976721486)),
 ('Alaska', 'Indiana', np.float64(0.9656589790206698)),
 ('Alaska', 'Iowa', np.float64(0.9674995406230946)),
 ('Alaska', 'Kansas', np.float64(0.9700735806335805)),
 ('Alaska', 'Kentucky', np.float64(0.9635735162271177)),
 ('Alaska', 'Louisiana', np.float64(0.8722983370552183)),
 ('Alaska', 'Maine', np.float64(0.9626256731926132)),
 ('Alaska', 'Maryland', np.float64(0.8661491682809546)),
 ('Alaska', 'Massachusetts', np.float64(0.9696407140106728)),
 ('Alaska', 'Michigan', np.float64(0.9609130145755891)),
 ('Alaska', 'Minnesota', np.float64(0.9710544469699891)),
 ('Alaska', 'Mississippi', np.float64(0.8269624058659123)),
 ('Alaska', 'Missouri', np.float64(0.9630283412373561)),
 ('Alaska', 'Montana', np.float64(0.9760433744460008)),
 ('Alaska', 'Nebraska', np.float64(0.9694013614500697)),
 ('Alaska', 'Nevada', np.float64(0.8874290078701618)),
 ('Alaska', 'New Hampshire', np.float64(0.9644770916340349)),
 ('Alaska', 'New Jersey', np.float64(0.9286428631991214)),
 ('Alaska', 'New Mexico', np.float64(0.6920083261789891)),
 ('Alaska', 'New York', np.float64(0.9303033650880927)),
 ('Alaska', 'North Carolina', np.float64(0.9361053969669315)),
 ('Alaska', 'North Dakota', np.float64(0.9758136264149292)),
 ('Alaska', 'Ohio', np.float64(0.9615100295026751)),
 ('Alaska', 'Oklahoma', np.float64(0.9881780339860429)),
 ('Alaska', 'Oregon', np.float64(0.972416426095755)),
 ('Alaska', 'Pennsylvania', np.float64(0.9647942327380913)),
 ('Alaska', 'Rhode Island', np.float64(0.9657418847842117)),
 ('Alaska', 'South Carolina', np.float64(0.9089693969650819)),
 ('Alaska', 'South Dakota', np.float64(0.9808748234590108)),
 ('Alaska', 'Tennessee', np.float64(0.9524987790341366)),
 ('Alaska', 'Texas', np.float64(0.7690879670609412)),
 ('Alaska', 'Utah', np.float64(0.9680797021853657)),
 ('Alaska', 'Vermont', np.float64(0.9621189617047785)),
 ('Alaska', 'Virginia', np.float64(0.9445102159522077)),
 ('Alaska', 'Washington', np.float64(0.9751679121530703)),
 ('Alaska', 'West Virginia', np.float64(0.960893537901065)),
 ('Alaska', 'Wisconsin', np.float64(0.9695107220586874)),
 ('Alaska', 'Wyoming', np.float64(0.9703627448103926)),
 ('Alaska', 'Puerto Rico', np.float64(0.11129559767852998)),
 ('Arizona', 'Alabama', np.float64(0.8532153881652852)),
 ('Arizona', 'Alaska', np.float64(0.9026314648157775)),
 ('Arizona', 'Arkansas', np.float64(0.9063079846094055)),
 ('Arizona', 'California', np.float64(0.9338928225441737)),
 ('Arizona', 'Colorado', np.float64(0.9764531765527142)),
 ('Arizona', 'Connecticut', np.float64(0.9574003581046276)),
 ('Arizona', 'Delaware', np.float64(0.9001647385340031)),
 ('Arizona', 'District of Columbia', np.float64(0.6662098831475624)),
 ('Arizona', 'Florida', np.float64(0.9788987938922208)),
 ('Arizona', 'Georgia', np.float64(0.8464482639610496)),
 ('Arizona', 'Hawaii', np.float64(0.5143013674974541)),
 ('Arizona', 'Idaho', np.float64(0.929921533781767)),
 ('Arizona', 'Illinois', np.float64(0.9585851918151176)),
 ('Arizona', 'Indiana', np.float64(0.9065467877276008)),
 ('Arizona', 'Iowa', np.float64(0.8992966657628899)),
 ('Arizona', 'Kansas', np.float64(0.9340604472048251)),
 ('Arizona', 'Kentucky', np.float64(0.8865595843085382)),
 ('Arizona', 'Louisiana', np.float64(0.827054394402121)),
 ('Arizona', 'Maine', np.float64(0.874224624168672)),
 ('Arizona', 'Maryland', np.float64(0.8539487063405385)),
 ('Arizona', 'Massachusetts', np.float64(0.9360179893894451)),
 ('Arizona', 'Michigan', np.float64(0.894087963404488)),
 ('Arizona', 'Minnesota', np.float64(0.8990676993941754)),
 ('Arizona', 'Mississippi', np.float64(0.7752124986583765)),
 ('Arizona', 'Missouri', np.float64(0.8905241098238862)),
 ('Arizona', 'Montana', np.float64(0.8867762061596616)),
 ('Arizona', 'Nebraska', np.float64(0.927477769132209)),
 ('Arizona', 'Nevada', np.float64(0.9901924342246191)),
 ('Arizona', 'New Hampshire', np.float64(0.8853314016831052)),
 ('Arizona', 'New Jersey', np.float64(0.9691751298981425)),
 ('Arizona', 'New Mexico', np.float64(0.9168164714931539)),
 ('Arizona', 'New York', np.float64(0.963198482630799)),
 ('Arizona', 'North Carolina', np.float64(0.9029150567804027)),
 ('Arizona', 'North Dakota', np.float64(0.8878080353850673)),
 ('Arizona', 'Ohio', np.float64(0.8872259176389969)),
 ('Arizona', 'Oklahoma', np.float64(0.933157307600465)),
 ('Arizona', 'Oregon', np.float64(0.9386690744217069)),
 ('Arizona', 'Pennsylvania', np.float64(0.908907521821336)),
 ('Arizona', 'Rhode Island', np.float64(0.9524238904925794)),
 ('Arizona', 'South Carolina', np.float64(0.8597014243380098)),
 ('Arizona', 'South Dakota', np.float64(0.8884426909932702)),
 ('Arizona', 'Tennessee', np.float64(0.8911980187533821)),
 ('Arizona', 'Texas', np.float64(0.9608864884780948)),
 ('Arizona', 'Utah', np.float64(0.9397720414558243)),
 ('Arizona', 'Vermont', np.float64(0.874947951952659)),
 ('Arizona', 'Virginia', np.float64(0.908482533198736)),
 ('Arizona', 'Washington', np.float64(0.9408473413271422)),
 ('Arizona', 'West Virginia', np.float64(0.8726988690210408)),
 ('Arizona', 'Wisconsin', np.float64(0.9061819715638704)),
 ('Arizona', 'Wyoming', np.float64(0.918569296300642)),
 ('Arizona', 'Puerto Rico', np.float64(0.49825959352631277)),
 ('Arkansas', 'Alabama', np.float64(0.9827781115549581)),
 ('Arkansas', 'Alaska', np.float64(0.9573184971397107)),
 ('Arkansas', 'Arizona', np.float64(0.9063079846094055)),
 ('Arkansas', 'California', np.float64(0.7384153531926175)),
 ('Arkansas', 'Colorado', np.float64(0.9687218582307586)),
 ('Arkansas', 'Connecticut', np.float64(0.9883751639872266)),
 ('Arkansas', 'Delaware', np.float64(0.9910222160736964)),
 ('Arkansas', 'District of Columbia', np.float64(0.7644289946625467)),
 ('Arkansas', 'Florida', np.float64(0.9437253538832346)),
 ('Arkansas', 'Georgia', np.float64(0.9459555438010858)),
 ('Arkansas', 'Hawaii', np.float64(0.45976586681966414)),
 ('Arkansas', 'Idaho', np.float64(0.9799977663832365)),
 ('Arkansas', 'Illinois', np.float64(0.9840160811734764)),
 ('Arkansas', 'Indiana', np.float64(0.9958948724501033)),
 ('Arkansas', 'Iowa', np.float64(0.9854598738324709)),
 ('Arkansas', 'Kansas', np.float64(0.989692559662381)),
 ('Arkansas', 'Kentucky', np.float64(0.9919774622690984)),
 ('Arkansas', 'Louisiana', np.float64(0.9574556163458542)),
 ('Arkansas', 'Maine', np.float64(0.9781393113627703)),
 ('Arkansas', 'Maryland', np.float64(0.9444561246076084)),
 ('Arkansas', 'Massachusetts', np.float64(0.990436829191579)),
 ('Arkansas', 'Michigan', np.float64(0.998852910645513)),
 ('Arkansas', 'Minnesota', np.float64(0.9910256498189587)),
 ('Arkansas', 'Mississippi', np.float64(0.9263367634568553)),
 ('Arkansas', 'Missouri', np.float64(0.9966783838091159)),
 ('Arkansas', 'Montana', np.float64(0.9767787225202238)),
 ('Arkansas', 'Nebraska', np.float64(0.9884957341393039)),
 ('Arkansas', 'Nevada', np.float64(0.9040322973076695)),
 ('Arkansas', 'New Hampshire', np.float64(0.9803160639738333)),
 ('Arkansas', 'New Jersey', np.float64(0.960073788863956)),
 ('Arkansas', 'New Mexico', np.float64(0.6704626049180455)),
 ('Arkansas', 'New York', np.float64(0.9667150960608603)),
 ('Arkansas', 'North Carolina', np.float64(0.9921883826820536)),
 ('Arkansas', 'North Dakota', np.float64(0.982134320355343)),
 ('Arkansas', 'Ohio', np.float64(0.9970475723935806)),
 ('Arkansas', 'Oklahoma', np.float64(0.9860906413679661)),
 ('Arkansas', 'Oregon', np.float64(0.9811339789856848)),
 ('Arkansas', 'Pennsylvania', np.float64(0.9974165591429944)),
 ('Arkansas', 'Rhode Island', np.float64(0.9857206428972136)),
 ('Arkansas', 'South Carolina', np.float64(0.9815078324535688)),
 ('Arkansas', 'South Dakota', np.float64(0.9781410092525257)),
 ('Arkansas', 'Tennessee', np.float64(0.9993439924444713)),
 ('Arkansas', 'Texas', np.float64(0.8008147633216118)),
 ('Arkansas', 'Utah', np.float64(0.9797350705352689)),
 ('Arkansas', 'Vermont', np.float64(0.9784367777607132)),
 ('Arkansas', 'Virginia', np.float64(0.9922284695856911)),
 ('Arkansas', 'Washington', np.float64(0.9798654988236942)),
 ('Arkansas', 'West Virginia', np.float64(0.9824658706845829)),
 ('Arkansas', 'Wisconsin', np.float64(0.9910811665365798)),
 ('Arkansas', 'Wyoming', np.float64(0.9814330755962373)),
 ('Arkansas', 'Puerto Rico', np.float64(0.10851411233390032)),
 ('California', 'Alabama', np.float64(0.6910373396673632)),
 ('California', 'Alaska', np.float64(0.7416111800267029)),
 ('California', 'Arizona', np.float64(0.9338928225441737)),
 ('California', 'Arkansas', np.float64(0.7384153531926175)),
 ('California', 'Colorado', np.float64(0.8539076847466507)),
 ('California', 'Connecticut', np.float64(0.8266788750584518)),
 ('California', 'Delaware', np.float64(0.7596025868296957)),
 ('California', 'District of Columbia', np.float64(0.6202775259455408)),
 ('California', 'Florida', np.float64(0.9033735011227922)),
 ('California', 'Georgia', np.float64(0.7334579918577523)),
 ('California', 'Hawaii', np.float64(0.638626979765879)),
 ('California', 'Idaho', np.float64(0.7605944890661719)),
 ('California', 'Illinois', np.float64(0.8450525304373874)),
 ('California', 'Indiana', np.float64(0.7303975350086814)),
 ('California', 'Iowa', np.float64(0.7162306591571558)),
 ('California', 'Kansas', np.float64(0.7737807953429325)),
 ('California', 'Kentucky', np.float64(0.6971055782093426)),
 ('California', 'Louisiana', np.float64(0.6838571174599564)),
 ('California', 'Maine', np.float64(0.6747328714034738)),
 ('California', 'Maryland', np.float64(0.754023180596613)),
 ('California', 'Massachusetts', np.float64(0.7900343515141672)),
 ('California', 'Michigan', np.float64(0.7201047651406552)),
 ('California', 'Minnesota', np.float64(0.7231484371207341)),
 ('California', 'Mississippi', np.float64(0.6329849227581771)),
 ('California', 'Missouri', np.float64(0.7078445448224978)),
 ('California', 'Montana', np.float64(0.6888932657991131)),
 ('California', 'Nebraska', np.float64(0.7607050564869297)),
 ('California', 'Nevada', np.float64(0.9549996640451381)),
 ('California', 'New Hampshire', np.float64(0.6949942990933046)),
 ('California', 'New Jersey', np.float64(0.8934553972136938)),
 ('California', 'New Mexico', np.float64(0.9538425520938495)),
 ('California', 'New York', np.float64(0.8798198493008991)),
 ('California', 'North Carolina', np.float64(0.7574179328077949)),
 ('California', 'North Dakota', np.float64(0.6930189251487826)),
 ('California', 'Ohio', np.float64(0.7047784580752574)),
 ('California', 'Oklahoma', np.float64(0.7711532887580694)),
 ('California', 'Oregon', np.float64(0.7844097592698577)),
 ('California', 'Pennsylvania', np.float64(0.7394331310115309)),
 ('California', 'Rhode Island', np.float64(0.8081276424216157)),
 ('California', 'South Carolina', np.float64(0.7042901647493889)),
 ('California', 'South Dakota', np.float64(0.6919337232969099)),
 ('California', 'Tennessee', np.float64(0.717672376127596)),
 ('California', 'Texas', np.float64(0.9771845343042149)),
 ('California', 'Utah', np.float64(0.7801180373551587)),
 ('California', 'Vermont', np.float64(0.6776705322264623)),
 ('California', 'Virginia', np.float64(0.7745151562823558)),
 ('California', 'Washington', np.float64(0.8049241214879673)),
 ('California', 'West Virginia', np.float64(0.6729696690694444)),
 ('California', 'Wisconsin', np.float64(0.7285332165378846)),
 ('California', 'Wyoming', np.float64(0.7397690592788428)),
 ('California', 'Puerto Rico', np.float64(0.7033780569347893)),
 ('Colorado', 'Alabama', np.float64(0.9181663981509592)),
 ('Colorado', 'Alaska', np.float64(0.9529090361921406)),
 ('Colorado', 'Arizona', np.float64(0.9764531765527142)),
 ('Colorado', 'Arkansas', np.float64(0.9687218582307586)),
 ('Colorado', 'California', np.float64(0.8539076847466507)),
 ('Colorado', 'Connecticut', np.float64(0.9937269035418531)),
 ('Colorado', 'Delaware', np.float64(0.9512590318430023)),
 ('Colorado', 'District of Columbia', np.float64(0.6747252268305808)),
 ('Colorado', 'Florida', np.float64(0.9716213602469881)),
 ('Colorado', 'Georgia', np.float64(0.8849408361649294)),
 ('Colorado', 'Hawaii', np.float64(0.504041160785644)),
 ('Colorado', 'Idaho', np.float64(0.9862761393158535)),
 ('Colorado', 'Illinois', np.float64(0.98625197779668)),
 ('Colorado', 'Indiana', np.float64(0.974294704230833)),
 ('Colorado', 'Iowa', np.float64(0.9717565136636774)),
 ('Colorado', 'Kansas', np.float64(0.9885138706013834)),
 ('Colorado', 'Kentucky', np.float64(0.9639158503419014)),
 ('Colorado', 'Louisiana', np.float64(0.8830239692092503)),
 ('Colorado', 'Maine', np.float64(0.9570773809863939)),
 ('Colorado', 'Maryland', np.float64(0.8889747780304845)),
 ('Colorado', 'Massachusetts', np.float64(0.9880976588804973)),
 ('Colorado', 'Michigan', np.float64(0.9642144088417813)),
 ('Colorado', 'Minnesota', np.float64(0.9708426085179556)),
 ('Colorado', 'Mississippi', np.float64(0.8338402863495818)),
 ('Colorado', 'Missouri', np.float64(0.9644646395867533)),
 ('Colorado', 'Montana', np.float64(0.9616363539892522)),
 ('Colorado', 'Nebraska', np.float64(0.9857548292027414)),
 ('Colorado', 'Nevada', np.float64(0.9645153197296248)),
 ('Colorado', 'New Hampshire', np.float64(0.9638569822859496)),
 ('Colorado', 'New Jersey', np.float64(0.9796109696027043)),
 ('Colorado', 'New Mexico', np.float64(0.8100912742326566)),
 ('Colorado', 'New York', np.float64(0.9775921518662356)),
 ('Colorado', 'North Carolina', np.float64(0.9532184866691173)),
 ('Colorado', 'North Dakota', np.float64(0.9626613193985193)),
 ('Colorado', 'Ohio', np.float64(0.9621035280614004)),
 ('Colorado', 'Oklahoma', np.float64(0.980453169034812)),
 ('Colorado', 'Oregon', np.float64(0.9901733583457137)),
 ('Colorado', 'Pennsylvania', np.float64(0.974597556769389)),
 ('Colorado', 'Rhode Island', np.float64(0.9953550177610495)),
 ('Colorado', 'South Carolina', np.float64(0.9199752654878162)),
 ('Colorado', 'South Dakota', np.float64(0.9606861775413615)),
 ('Colorado', 'Tennessee', np.float64(0.9596060857204474)),
 ('Colorado', 'Texas', np.float64(0.8909436727504226)),
 ('Colorado', 'Utah', np.float64(0.9906113783341054)),
 ('Colorado', 'Vermont', np.float64(0.9577724044484002)),
 ('Colorado', 'Virginia', np.float64(0.9592519308469747)),
 ('Colorado', 'Washington', np.float64(0.9886775311893314)),
 ('Colorado', 'West Virginia', np.float64(0.9564080790272395)),
 ('Colorado', 'Wisconsin', np.float64(0.9750258908662843)),
 ('Colorado', 'Wyoming', np.float64(0.9806268954507127)),
 ('Colorado', 'Puerto Rico', np.float64(0.3073630503384241)),
 ('Connecticut', 'Alabama', np.float64(0.9553103684194725)),
 ('Connecticut', 'Alaska', np.float64(0.9590604204992825)),
 ('Connecticut', 'Arizona', np.float64(0.9574003581046276)),
 ('Connecticut', 'Arkansas', np.float64(0.9883751639872266)),
 ('Connecticut', 'California', np.float64(0.8266788750584518)),
 ('Connecticut', 'Colorado', np.float64(0.9937269035418531)),
 ('Connecticut', 'Delaware', np.float64(0.9791809054770365)),
 ('Connecticut', 'District of Columbia', np.float64(0.7362175358432341)),
 ('Connecticut', 'Florida', np.float64(0.9736557546833453)),
 ('Connecticut', 'Georgia', np.float64(0.9267157799618537)),
 ('Connecticut', 'Hawaii', np.float64(0.5120559533981484)),
 ('Connecticut', 'Idaho', np.float64(0.9859206309998244)),
 ('Connecticut', 'Illinois', np.float64(0.9966539886803345)),
 ('Connecticut', 'Indiana', np.float64(0.9875770039959161)),
 ('Connecticut', 'Iowa', np.float64(0.9796099286926367)),
 ('Connecticut', 'Kansas', np.float64(0.9936139599257)),
 ('Connecticut', 'Kentucky', np.float64(0.9783338406041605)),
 ('Connecticut', 'Louisiana', np.float64(0.927388615839199)),
 ('Connecticut', 'Maine', np.float64(0.9659674201611346)),
 ('Connecticut', 'Maryland', np.float64(0.9298164508532962)),
 ('Connecticut', 'Massachusetts', np.float64(0.9959488320060271)),
 ('Connecticut', 'Michigan', np.float64(0.9845908707422416)),
 ('Connecticut', 'Minnesota', np.float64(0.9832727802731409)),
 ('Connecticut', 'Mississippi', np.float64(0.8867169090085499)),
 ('Connecticut', 'Missouri', np.float64(0.9821914581071868)),
 ('Connecticut', 'Montana', np.float64(0.9679265099675072)),
 ('Connecticut', 'Nebraska', np.float64(0.9906364876410749)),
 ('Connecticut', 'Nevada', np.float64(0.9547940473297636)),
 ('Connecticut', 'New Hampshire', np.float64(0.9718368736394335)),

In [24]:
age_columns = ['Age0_18', 'Age_19_25', 'Age_26_34', 'Age_35_54', 'Age_55_64', 'Age_65_plus']
age_similarity = compute_cosine_similarity(data, age_columns)
age_similarity

[('Alabama', 'Alaska', np.float64(0.9890460096780322)),
 ('Alabama', 'Arizona', np.float64(0.9988976158758917)),
 ('Alabama', 'Arkansas', np.float64(0.9995096916863628)),
 ('Alabama', 'California', np.float64(0.996089066985675)),
 ('Alabama', 'Colorado', np.float64(0.9959837164034675)),
 ('Alabama', 'Connecticut', np.float64(0.9983735900861958)),
 ('Alabama', 'Delaware', np.float64(0.9980908911167148)),
 ('Alabama', 'District of Columbia', np.float64(0.9583185024907372)),
 ('Alabama', 'Florida', np.float64(0.9942481155288824)),
 ('Alabama', 'Georgia', np.float64(0.9957790780355169)),
 ('Alabama', 'Hawaii', np.float64(0.9976775338843018)),
 ('Alabama', 'Idaho', np.float64(0.9963529442086612)),
 ('Alabama', 'Illinois', np.float64(0.9988461786032494)),
 ('Alabama', 'Indiana', np.float64(0.9993027706710572)),
 ('Alabama', 'Iowa', np.float64(0.9996986187893946)),
 ('Alabama', 'Kansas', np.float64(0.99811087133644)),
 ('Alabama', 'Kentucky', np.float64(0.9997874455622177)),
 ('Alabama', 'Louisiana', np.float64(0.998415759816853)),
 ('Alabama', 'Maine', np.float64(0.9902628606349386)),
 ('Alabama', 'Maryland', np.float64(0.9981820487462933)),
 ('Alabama', 'Massachusetts', np.float64(0.9971455326118237)),
 ('Alabama', 'Michigan', np.float64(0.9995659773474095)),
 ('Alabama', 'Minnesota', np.float64(0.9990526580946042)),
 ('Alabama', 'Mississippi', np.float64(0.9986440066662327)),
 ('Alabama', 'Missouri', np.float64(0.9996893581833973)),
 ('Alabama', 'Montana', np.float64(0.9979730655012303)),
 ('Alabama', 'Nebraska', np.float64(0.9978563667787517)),
 ('Alabama', 'Nevada', np.float64(0.998390095122494)),
 ('Alabama', 'New Hampshire', np.float64(0.9940143136590023)),
 ('Alabama', 'New Jersey', np.float64(0.9985177111013402)),
 ('Alabama', 'New Mexico', np.float64(0.9988032411182735)),
 ('Alabama', 'New York', np.float64(0.9976966771973917)),
 ('Alabama', 'North Carolina', np.float64(0.9993513730404211)),
 ('Alabama', 'North Dakota', np.float64(0.9963772636472236)),
 ('Alabama', 'Ohio', np.float64(0.9998000300211685)),
 ('Alabama', 'Oklahoma', np.float64(0.9977951372749532)),
 ('Alabama', 'Oregon', np.float64(0.9982351938177967)),
 ('Alabama', 'Pennsylvania', np.float64(0.9982827934837948)),
 ('Alabama', 'Rhode Island', np.float64(0.9972879587863703)),
 ('Alabama', 'South Carolina', np.float64(0.9995787700189511)),
 ('Alabama', 'South Dakota', np.float64(0.9979194937221969)),
 ('Alabama', 'Tennessee', np.float64(0.9995505777407552)),
 ('Alabama', 'Texas', np.float64(0.9897474377461211)),
 ('Alabama', 'Utah', np.float64(0.9729242929574072)),
 ('Alabama', 'Vermont', np.float64(0.99234118822464)),
 ('Alabama', 'Virginia', np.float64(0.9988528384074655)),
 ('Alabama', 'Washington', np.float64(0.9980562559095795)),
 ('Alabama', 'West Virginia', np.float64(0.9958212197738182)),
 ('Alabama', 'Wisconsin', np.float64(0.9997099088698949)),
 ('Alabama', 'Wyoming', np.float64(0.9979748359158607)),
 ('Alabama', 'Puerto Rico', np.float64(0.9946642800772774)),
 ('Alaska', 'Alabama', np.float64(0.9890460096780322)),
 ('Alaska', 'Arizona', np.float64(0.9878192964549783)),
 ('Alaska', 'Arkansas', np.float64(0.9904437441264903)),
 ('Alaska', 'California', np.float64(0.9957512667972234)),
 ('Alaska', 'Colorado', np.float64(0.9954517366721863)),
 ('Alaska', 'Connecticut', np.float64(0.9842645743632497)),
 ('Alaska', 'Delaware', np.float64(0.9803191345740891)),
 ('Alaska', 'District of Columbia', np.float64(0.9656815952430567)),
 ('Alaska', 'Florida', np.float64(0.9692711360035347)),
 ('Alaska', 'Georgia', np.float64(0.996977261212619)),
 ('Alaska', 'Hawaii', np.float64(0.9818690686503471)),
 ('Alaska', 'Idaho', np.float64(0.9935459295640319)),
 ('Alaska', 'Illinois', np.float64(0.9937302515160031)),
 ('Alaska', 'Indiana', np.float64(0.9937000099828474)),
 ('Alaska', 'Iowa', np.float64(0.9903394493951059)),
 ('Alaska', 'Kansas', np.float64(0.9941080902303785)),
 ('Alaska', 'Kentucky', np.float64(0.991056299330874)),
 ('Alaska', 'Louisiana', np.float64(0.9953486136303814)),
 ('Alaska', 'Maine', np.float64(0.9632411017333855)),
 ('Alaska', 'Maryland', np.float64(0.9924842442417513)),
 ('Alaska', 'Massachusetts', np.float64(0.9857307151620438)),
 ('Alaska', 'Michigan', np.float64(0.9863948113364363)),
 ('Alaska', 'Minnesota', np.float64(0.993738999045554)),
 ('Alaska', 'Mississippi', np.float64(0.9920866640302161)),
 ('Alaska', 'Missouri', np.float64(0.9900664770187515)),
 ('Alaska', 'Montana', np.float64(0.9799289279467599)),
 ('Alaska', 'Nebraska', np.float64(0.9949451358251777)),
 ('Alaska', 'Nevada', np.float64(0.9925080047982386)),
 ('Alaska', 'New Hampshire', np.float64(0.9743973206824249)),
 ('Alaska', 'New Jersey', np.float64(0.9897608643104185)),
 ('Alaska', 'New Mexico', np.float64(0.9885379677306099)),
 ('Alaska', 'New York', np.float64(0.9881179936189002)),
 ('Alaska', 'North Carolina', np.float64(0.9908271120910433)),
 ('Alaska', 'North Dakota', np.float64(0.9941228509884938)),
 ('Alaska', 'Ohio', np.float64(0.9888555734053985)),
 ('Alaska', 'Oklahoma', np.float64(0.9947995846971507)),
 ('Alaska', 'Oregon', np.float64(0.9851330157009481)),
 ('Alaska', 'Pennsylvania', np.float64(0.981639318549963)),
 ('Alaska', 'Rhode Island', np.float64(0.9826154112354817)),
 ('Alaska', 'South Carolina', np.float64(0.9852329144882577)),
 ('Alaska', 'South Dakota', np.float64(0.9913953296181433)),
 ('Alaska', 'Tennessee', np.float64(0.9912097057989341)),
 ('Alaska', 'Texas', np.float64(0.9988327354140953)),
 ('Alaska', 'Utah', np.float64(0.9911623816656234)),
 ('Alaska', 'Vermont', np.float64(0.9669955985651106)),
 ('Alaska', 'Virginia', np.float64(0.9919808801095862)),
 ('Alaska', 'Washington', np.float64(0.9930559970773045)),
 ('Alaska', 'West Virginia', np.float64(0.9720875599646011)),
 ('Alaska', 'Wisconsin', np.float64(0.9877966684048181)),
 ('Alaska', 'Wyoming', np.float64(0.9921169845076856)),
 ('Alaska', 'Puerto Rico', np.float64(0.9697314844995928)),
 ('Arizona', 'Alabama', np.float64(0.9988976158758917)),
 ('Arizona', 'Alaska', np.float64(0.9878192964549783)),
 ('Arizona', 'Arkansas', np.float64(0.999502448804678)),
 ('Arizona', 'California', np.float64(0.9952045372769043)),
 ('Arizona', 'Colorado', np.float64(0.9945713706653309)),
 ('Arizona', 'Connecticut', np.float64(0.9953113149528809)),
 ('Arizona', 'Delaware', np.float64(0.9970866663946398)),
 ('Arizona', 'District of Columbia', np.float64(0.9587040960551364)),
 ('Arizona', 'Florida', np.float64(0.9937605528329956)),
 ('Arizona', 'Georgia', np.float64(0.9942562180527768)),
 ('Arizona', 'Hawaii', np.float64(0.9974918069944795)),
 ('Arizona', 'Idaho', np.float64(0.9971408497445613)),
 ('Arizona', 'Illinois', np.float64(0.9973176940122779)),
 ('Arizona', 'Indiana', np.float64(0.9983160151386901)),
 ('Arizona', 'Iowa', np.float64(0.9991761596454929)),
 ('Arizona', 'Kansas', np.float64(0.9981639592760836)),
 ('Arizona', 'Kentucky', np.float64(0.9981695386450308)),
 ('Arizona', 'Louisiana', np.float64(0.9979544645943036)),
 ('Arizona', 'Maine', np.float64(0.9870038098014564)),
 ('Arizona', 'Maryland', np.float64(0.9955835690954672)),
 ('Arizona', 'Massachusetts', np.float64(0.9947311912790684)),
 ('Arizona', 'Michigan', np.float64(0.9977807874393138)),
 ('Arizona', 'Minnesota', np.float64(0.9975709817144447)),
 ('Arizona', 'Mississippi', np.float64(0.9980429579994671)),
 ('Arizona', 'Missouri', np.float64(0.998931376054293)),
 ('Arizona', 'Montana', np.float64(0.9968740963808868)),
 ('Arizona', 'Nebraska', np.float64(0.9980631308929999)),
 ('Arizona', 'Nevada', np.float64(0.9973585716346065)),
 ('Arizona', 'New Hampshire', np.float64(0.9896337706907046)),
 ('Arizona', 'New Jersey', np.float64(0.9958074163384296)),
 ('Arizona', 'New Mexico', np.float64(0.9992843113205021)),
 ('Arizona', 'New York', np.float64(0.9960073093988449)),
 ('Arizona', 'North Carolina', np.float64(0.9978334919624101)),
 ('Arizona', 'North Dakota', np.float64(0.9964372204432093)),
 ('Arizona', 'Ohio', np.float64(0.9983782377117465)),
 ('Arizona', 'Oklahoma', np.float64(0.9981958309929673)),
 ('Arizona', 'Oregon', np.float64(0.997147938968682)),
 ('Arizona', 'Pennsylvania', np.float64(0.9965110100347137)),
 ('Arizona', 'Rhode Island', np.float64(0.9948095430124657)),
 ('Arizona', 'South Carolina', np.float64(0.9985477013388473)),
 ('Arizona', 'South Dakota', np.float64(0.9984605189073582)),
 ('Arizona', 'Tennessee', np.float64(0.9982054523895239)),
 ('Arizona', 'Texas', np.float64(0.9898301893518706)),
 ('Arizona', 'Utah', np.float64(0.9759899089294567)),
 ('Arizona', 'Vermont', np.float64(0.9890700088419758)),
 ('Arizona', 'Virginia', np.float64(0.996879491587043)),
 ('Arizona', 'Washington', np.float64(0.9967592515861661)),
 ('Arizona', 'West Virginia', np.float64(0.9938869846526016)),
 ('Arizona', 'Wisconsin', np.float64(0.9977706826649873)),
 ('Arizona', 'Wyoming', np.float64(0.9975116257139357)),
 ('Arizona', 'Puerto Rico', np.float64(0.9941472045823846)),
 ('Arkansas', 'Alabama', np.float64(0.9995096916863628)),
 ('Arkansas', 'Alaska', np.float64(0.9904437441264903)),
 ('Arkansas', 'Arizona', np.float64(0.999502448804678)),
 ('Arkansas', 'California', np.float64(0.9959661138456184)),
 ('Arkansas', 'Colorado', np.float64(0.9954297671421586)),
 ('Arkansas', 'Connecticut', np.float64(0.996148543173472)),
 ('Arkansas', 'Delaware', np.float64(0.9965788503514033)),
 ('Arkansas', 'District of Columbia', np.float64(0.9560447693485672)),
 ('Arkansas', 'Florida', np.float64(0.992189545907391)),
 ('Arkansas', 'Georgia', np.float64(0.9962528383902025)),
 ('Arkansas', 'Hawaii', np.float64(0.9967458803434135)),
 ('Arkansas', 'Idaho', np.float64(0.9983495151532351)),
 ('Arkansas', 'Illinois', np.float64(0.9983149154768011)),
 ('Arkansas', 'Indiana', np.float64(0.9994566496460744)),
 ('Arkansas', 'Iowa', np.float64(0.9998309413015618)),
 ('Arkansas', 'Kansas', np.float64(0.9992256812999059)),
 ('Arkansas', 'Kentucky', np.float64(0.9992291528864641)),
 ('Arkansas', 'Louisiana', np.float64(0.9990582222400736)),
 ('Arkansas', 'Maine', np.float64(0.9865458679140011)),
 ('Arkansas', 'Maryland', np.float64(0.9969669088640372)),
 ('Arkansas', 'Massachusetts', np.float64(0.9948621458774961)),
 ('Arkansas', 'Michigan', np.float64(0.998268856987986)),
 ('Arkansas', 'Minnesota', np.float64(0.9986504914371305)),
 ('Arkansas', 'Mississippi', np.float64(0.9994160486271387)),
 ('Arkansas', 'Missouri', np.float64(0.9993187398921)),
 ('Arkansas', 'Montana', np.float64(0.9966049492930159)),
 ('Arkansas', 'Nebraska', np.float64(0.9989682845063121)),
 ('Arkansas', 'Nevada', np.float64(0.9978921687334716)),
 ('Arkansas', 'New Hampshire', np.float64(0.9902581551718553)),
 ('Arkansas', 'New Jersey', np.float64(0.9970903480691942)),
 ('Arkansas', 'New Mexico', np.float64(0.9994017783638892)),
 ('Arkansas', 'New York', np.float64(0.9959853267800665)),
 ('Arkansas', 'North Carolina', np.float64(0.998727376871596)),
 ('Arkansas', 'North Dakota', np.float64(0.9967519460253657)),
 ('Arkansas', 'Ohio', np.float64(0.9989819547605342)),
 ('Arkansas', 'Oklahoma', np.float64(0.9990638386155837)),
 ('Arkansas', 'Oregon', np.float64(0.996699160399784)),
 ('Arkansas', 'Pennsylvania', np.float64(0.9964262471045311)),
 ('Arkansas', 'Rhode Island', np.float64(0.9947688919345954)),
 ('Arkansas', 'South Carolina', np.float64(0.9986457944680345)),
 ('Arkansas', 'South Dakota', np.float64(0.998845389509065)),
 ('Arkansas', 'Tennessee', np.float64(0.9989004499828351)),
 ('Arkansas', 'Texas', np.float64(0.991918924180659)),
 ('Arkansas', 'Utah', np.float64(0.9782368858510011)),
 ('Arkansas', 'Vermont', np.float64(0.988703900716857)),
 ('Arkansas', 'Virginia', np.float64(0.9979152590778583)),
 ('Arkansas', 'Washington', np.float64(0.997282867401676)),
 ('Arkansas', 'West Virginia', np.float64(0.9936459697159079)),
 ('Arkansas', 'Wisconsin', np.float64(0.9985687923352359)),
 ('Arkansas', 'Wyoming', np.float64(0.9984309577089555)),
 ('Arkansas', 'Puerto Rico', np.float64(0.9927422216378672)),
 ('California', 'Alabama', np.float64(0.996089066985675)),
 ('California', 'Alaska', np.float64(0.9957512667972234)),
 ('California', 'Arizona', np.float64(0.9952045372769043)),
 ('California', 'Arkansas', np.float64(0.9959661138456184)),
 ('California', 'Colorado', np.float64(0.9997691005030982)),
 ('California', 'Connecticut', np.float64(0.9939927902434889)),
 ('California', 'Delaware', np.float64(0.9913410720706265)),
 ('California', 'District of Columbia', np.float64(0.9749156263127813)),
 ('California', 'Florida', np.float64(0.9850663242235932)),
 ('California', 'Georgia', np.float64(0.9985916273721146)),
 ('California', 'Hawaii', np.float64(0.9921719685610308)),
 ('California', 'Idaho', np.float64(0.9943067784938251)),
 ('California', 'Illinois', np.float64(0.9989852124342059)),
 ('California', 'Indiana', np.float64(0.9978553501798514)),
 ('California', 'Iowa', np.float64(0.9957419575662476)),
 ('California', 'Kansas', np.float64(0.9962882010346008)),
 ('California', 'Kentucky', np.float64(0.9970473768439914)),
 ('California', 'Louisiana', np.float64(0.9980769960451902)),
 ('California', 'Maine', np.float64(0.9789683161266902)),
 ('California', 'Maryland', np.float64(0.9983002068336961)),
 ('California', 'Massachusetts', np.float64(0.9958361916693317)),
 ('California', 'Michigan', np.float64(0.994883359199249)),
 ('California', 'Minnesota', np.float64(0.998313079264539)),
 ('California', 'Mississippi', np.float64(0.9956347008396151)),
 ('California', 'Missouri', np.float64(0.9964297279753642)),
 ('California', 'Montana', np.float64(0.9902009921143593)),
 ('California', 'Nebraska', np.float64(0.9969272449823277)),
 ('California', 'Nevada', np.float64(0.9990198103514898)),
 ('California', 'New Hampshire', np.float64(0.9871436501385037)),
 ('California', 'New Jersey', np.float64(0.9970277730527731)),
 ('California', 'New Mexico', np.float64(0.9939850711480482)),
 ('California', 'New York', np.float64(0.9974431136579565)),
 ('California', 'North Carolina', np.float64(0.997564798837965)),
 ('California', 'North Dakota', np.float64(0.9972897742642083)),
 ('California', 'Ohio', np.float64(0.9958705624249047)),
 ('California', 'Oklahoma', np.float64(0.9968870842195755)),
 ('California', 'Oregon', np.float64(0.9954785402917992)),
 ('California', 'Pennsylvania', np.float64(0.9923220285088759)),
 ('California', 'Rhode Island', np.float64(0.9938582348426411)),
 ('California', 'South Carolina', np.float64(0.9944586009632478)),
 ('California', 'South Dakota', np.float64(0.9946136210466328)),
 ('California', 'Tennessee', np.float64(0.9977678941474848)),
 ('California', 'Texas', np.float64(0.9959245682011615)),
 ('California', 'Utah', np.float64(0.981521733991745)),
 ('California', 'Vermont', np.float64(0.9821938106800561)),
 ('California', 'Virginia', np.float64(0.9984458839970782)),
 ('California', 'Washington', np.float64(0.9990865462827561)),
 ('California', 'West Virginia', np.float64(0.9855156789107431)),
 ('California', 'Wisconsin', np.float64(0.9952847921472974)),
 ('California', 'Wyoming', np.float64(0.9947166198641543)),
 ('California', 'Puerto Rico', np.float64(0.9859559442568502)),
 ('Colorado', 'Alabama', np.float64(0.9959837164034675)),
 ('Colorado', 'Alaska', np.float64(0.9954517366721863)),
 ('Colorado', 'Arizona', np.float64(0.9945713706653309)),
 ('Colorado', 'Arkansas', np.float64(0.9954297671421586)),
 ('Colorado', 'California', np.float64(0.9997691005030982)),
 ('Colorado', 'Connecticut', np.float64(0.994745311849304)),
 ('Colorado', 'Delaware', np.float64(0.992001324266366)),
 ('Colorado', 'District of Columbia', np.float64(0.9765423964089072)),
 ('Colorado', 'Florida', np.float64(0.985646357091085)),
 ('Colorado', 'Georgia', np.float64(0.9980356893951907)),
 ('Colorado', 'Hawaii', np.float64(0.9928441411300186)),
 ('Colorado', 'Idaho', np.float64(0.9932894093498443)),
 ('Colorado', 'Illinois', np.float64(0.9990494923133355)),
 ('Colorado', 'Indiana', np.float64(0.9975208342261607)),
 ('Colorado', 'Iowa', np.float64(0.9955301624783484)),
 ('Colorado', 'Kansas', np.float64(0.9956505781287002)),
 ('Colorado', 'Kentucky', np.float64(0.9970672348888054)),
 ('Colorado', 'Louisiana', np.float64(0.99762484452888)),
 ('Colorado', 'Maine', np.float64(0.9808298819363374)),
 ('Colorado', 'Maryland', np.float64(0.9987191292106428)),
 ('Colorado', 'Massachusetts', np.float64(0.996797275878599)),
 ('Colorado', 'Michigan', np.float64(0.9951804115660126)),
 ('Colorado', 'Minnesota', np.float64(0.998547299663973)),
 ('Colorado', 'Mississippi', np.float64(0.9947677590388264)),
 ('Colorado', 'Missouri', np.float64(0.9966233022469073)),
 ('Colorado', 'Montana', np.float64(0.9906245442589464)),
 ('Colorado', 'Nebraska', np.float64(0.9964873181765187)),
 ('Colorado', 'Nevada', np.float64(0.9989957307103456)),
 ('Colorado', 'New Hampshire', np.float64(0.988807321996699)),
 ('Colorado', 'New Jersey', np.float64(0.9974079189650686)),
 ('Colorado', 'New Mexico', np.float64(0.9935767409757267)),
 ('Colorado', 'New York', np.float64(0.9980013550817639)),
 ('Colorado', 'North Carolina', np.float64(0.997547862136109)),
 ('Colorado', 'North Dakota', np.float64(0.997096739157441)),
 ('Colorado', 'Ohio', np.float64(0.9961714395082)),
 ('Colorado', 'Oklahoma', np.float64(0.9962918762397817)),
 ('Colorado', 'Oregon', np.float64(0.9961234764740894)),
 ('Colorado', 'Pennsylvania', np.float64(0.9931430726475083)),
 ('Colorado', 'Rhode Island', np.float64(0.9947233567460367)),
 ('Colorado', 'South Carolina', np.float64(0.9946201431206798)),
 ('Colorado', 'South Dakota', np.float64(0.9945111713135582)),
 ('Colorado', 'Tennessee', np.float64(0.9979269110192623)),
 ('Colorado', 'Texas', np.float64(0.9947442988469339)),
 ('Colorado', 'Utah', np.float64(0.9788282253795716)),
 ('Colorado', 'Vermont', np.float64(0.983609577327254)),
 ('Colorado', 'Virginia', np.float64(0.9985700300239315)),
 ('Colorado', 'Washington', np.float64(0.999447970220136)),
 ('Colorado', 'West Virginia', np.float64(0.9861084740283893)),
 ('Colorado', 'Wisconsin', np.float64(0.9956427821146168)),
 ('Colorado', 'Wyoming', np.float64(0.994904240309628)),
 ('Colorado', 'Puerto Rico', np.float64(0.9857479003959005)),
 ('Connecticut', 'Alabama', np.float64(0.9983735900861958)),
 ('Connecticut', 'Alaska', np.float64(0.9842645743632497)),
 ('Connecticut', 'Arizona', np.float64(0.9953113149528809)),
 ('Connecticut', 'Arkansas', np.float64(0.996148543173472)),
 ('Connecticut', 'California', np.float64(0.9939927902434889)),
 ('Connecticut', 'Colorado', np.float64(0.994745311849304)),
 ('Connecticut', 'Delaware', np.float64(0.9983357279614111)),
 ('Connecticut', 'District of Columbia', np.float64(0.9604231005763386)),
 ('Connecticut', 'Florida', np.float64(0.9956522283843485)),
 ('Connecticut', 'Georgia', np.float64(0.9928025787973085)),
 ('Connecticut', 'Hawaii', np.float64(0.9973095971154542)),
 ('Connecticut', 'Idaho', np.float64(0.9903463126490222)),
 ('Connecticut', 'Illinois', np.float64(0.99748841994686)),
 ('Connecticut', 'Indiana', np.float64(0.9965514886620499)),
 ('Connecticut', 'Iowa', np.float64(0.9969140540072408)),
 ('Connecticut', 'Kansas', np.float64(0.9934952830649222)),
 ('Connecticut', 'Kentucky', np.float64(0.9984198891342987)),
 ('Connecticut', 'Louisiana', np.float64(0.994730349225169)),
 ('Connecticut', 'Maine', np.float64(0.9946974301578712)),
 ('Connecticut', 'Maryland', np.float64(0.9981957659884002)),
 ('Connecticut', 'Massachusetts', np.float64(0.9989745516695074)),
 ('Connecticut', 'Michigan', np.float64(0.9992454223124455)),
 ('Connecticut', 'Minnesota', np.float64(0.9974781710734997)),
 ('Connecticut', 'Mississippi', np.float64(0.9947052991162093)),
 ('Connecticut', 'Missouri', np.float64(0.9979211410528064)),
 ('Connecticut', 'Montana', np.float64(0.9975715387778817)),
 ('Connecticut', 'Nebraska', np.float64(0.9933623296971825)),
 ('Connecticut', 'Nevada', np.float64(0.9971612858433805)),
 ('Connecticut', 'New Hampshire', np.float64(0.9983535252187448)),
 ('Connecticut', 'New Jersey', np.float64(0.9989779323712111)),

__A9.__ _(3 points)_ Next, we would like to investigate which locations are the most or least similar given these different types of demographics. To support these investigations, write a function called `get_min_max_similarity`. The function should take a `similarity_list`, which is the output from the `compute_cosite_similarity()` method you wrote in A8. The function should return two values `min_similarity` and `max_similarity`. These correspond to the entries from the provided `similarity_list` that have the smallest and largest similarity respectively.

For example `min_similarity` and `max_similarity` will have the format `(<location 1>, <location 2>, <cosine similarity>)`.

In [25]:
# A9:Function(3/3)

def get_min_max_similarity(similarity_list):
    
    min_similarity = min(similarity_list, key=lambda x: x[2])

    max_similarity = max(similarity_list, key=lambda x: x[2])
    
    return min_similarity, max_similarity

To test this function, let's apply it to compare states in terms of both race and age similarity.

In [26]:
# A9:SanityCheck

min_race_similarity, max_race_similarity = get_min_max_similarity(race_similarity)
print("The locations with least similar race demographics: {}".format(min_race_similarity))
print("The locations with most similar race demographics: {}".format(max_race_similarity))

The locations with least similar race demographics: ('West Virginia', 'Puerto Rico', np.float64(0.01950610252950971))
The locations with most similar race demographics: ('Maine', 'Vermont', np.float64(0.9999496582673306))

In [27]:
# A9:SanityCheck

min_age_similarity, max_age_similarity = get_min_max_similarity(age_similarity)
print("The locations with least similar age demographics: {}".format(min_age_similarity))
print("The locations with most similar age demographics: {}".format(max_age_similarity))

The locations with least similar age demographics: ('Maine', 'Utah', np.float64(0.9321725437407273))
The locations with most similar age demographics: ('Nebraska', 'Oklahoma', np.float64(0.9999533208314442))